# .streamlit/secrets.toml
SUPABASE_URL = "https://zpdhqskfscwlcfrfzxwk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZGhxc2tmc2N3bGNmcmZ6eHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyMDAxNTMsImV4cCI6MjA4Mzc3NjE1M30.GBGGCdaeobKUkl1jviMukLu_quVh1H7gVDnT01FTrEM"